export const data = [
  {
    id: "1",
    name: "Spaghetti Carbonara",
    description: "Classic Italian pasta dish with bacon, eggs, and cheese.",
    user: "ItalianChef",
    goto: "#",
    isFavorite: false,
  },
  {
    id: "2",
    name: "Tofu Stir-Fry",
    description: "Healthy and flavorful stir-fry with tofu, vegetables, and soy sauce.",
    user: "HealthyEats",
    goto: "#",
    isFavorite: false,
  },
  {
    id: "3",
    name: "Chicken Tikka Masala",
    description: "Rich and creamy Indian curry dish with marinated chicken.",
    user: "SpiceMaster",
    goto: "#",
    isFavorite: false,
  },
  {
    id: "4",
    name: "Vegetable Pad Thai",
    description: "Thai noodle dish with mixed vegetables, tofu, and peanuts.",
    user: "ThaiFoodie",
    goto: "#",
    isFavorite: false,
  },
  {
    id: "5",
    name: "Beef Tacos",
    description: "Mexican street food classic with seasoned beef, salsa, and toppings.",
    user: "TacoTuesday",
    goto: "#",
    isFavorite: false,
  },
  {
    id: "6",
    name: "Sushi Rolls",
    description: "Assorted sushi rolls with fresh fish, avocado, and rice.",
    user: "SushiMaster",
    goto: "#",
    isFavorite: false,
  },
  {
    id: "7",
    name: "Pesto Pasta",
    description: "Pasta dish with basil pesto, cherry tomatoes, and pine nuts.",
    user: "PastaLover",
    goto: "#",
    isFavorite: false,
  },
  {
    id: "8",
    name: "Hawaiian Pizza",
    description: "Pizza topped with ham, pineapple, and mozzarella cheese.",
    user: "PizzaFanatic",
    goto: "#",
    isFavorite: false,
  },
  {
    id: "9",
    name: "Mushroom Risotto",
    description: "Creamy Italian rice dish cooked with mushrooms and Parmesan cheese.",
    user: "RisottoChef",
    goto: "#",
    isFavorite: false,
  },
  {
    id: "10",
    name: "Vegetarian Chili",
    description: "Hearty chili made with beans, vegetables, and spices.",
    user: "ChiliLover",
    goto: "#",
    isFavorite: false,
  },
  {
    id: "11",
    name: "Greek Salad",
    description: "Refreshing salad with tomatoes, cucumbers, olives, and feta cheese.",
    user: "SaladEnthusiast",
    goto: "#",
    isFavorite: false,
  },
];
